# a neural network with a perceptron

In [4]:
import numpy as np 
import pandas as pd
import sklearn
from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [6]:
from sklearn.linear_model import Perceptron

In [8]:
iris = datasets.load_iris()

X = iris.data
y = iris.target
X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [10]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [11]:
standardized_X_test[0:10,]

array([[-0.05268999, -0.73430828,  0.17063753,  0.01536523],
       [-1.15917986,  1.60508093, -1.26271774, -1.2138533 ],
       [-0.05268999, -0.53935918,  0.23889255, -0.2919394 ],
       [-1.47531982, -1.12420648, -0.30714756, -0.2919394 ],
       [ 0.89572989,  0.43538632,  1.0579527 ,  1.70554071],
       [ 0.42151995, -0.34441008,  0.64842262,  0.01536523],
       [ 0.89572989,  0.43538632,  0.5119126 ,  0.47632218],
       [-1.47531982,  0.24043722, -1.53573779, -1.52115793],
       [-1.31724984,  0.63033543, -1.60399281, -1.52115793],
       [ 0.73765991, -0.92925738,  0.78493265,  0.47632218]])

In [14]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [19]:
y_pred = perceptron.predict(standardized_X_test)

In [20]:
print(y_test)

[1 0 1 1 2 1 1 0 0 1 2 2 0 0 1 1 1 2 1 1 1 0 1 2 1 0 1 2 0 2]


In [21]:
print(y_pred)

[1 0 1 1 2 1 2 0 0 1 2 2 0 0 2 1 1 2 1 1 1 0 1 2 1 0 2 2 0 2]


In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.80      0.89        15
           2       0.70      1.00      0.82         7

    accuracy                           0.90        30
   macro avg       0.90      0.93      0.90        30
weighted avg       0.93      0.90      0.90        30

